### ISSUE TITLE
I have run the code without error, but the output kivy gui does not show the car widget. I can draw the sand lines, and when I close the Kivy gui window, it stops responding. Cannot figure whether it has something to do with my system or the code. 

### ISSUE THREAD

**Issue by AzadSajib** [Jerry2001Qu/Self-Driving-Car#3]
![image](https://user-images.githubusercontent.com/39127915/99808441-117f9100-2b6b-11eb-87ee-20e2bbc96f5a.png)

**Comment by sven-borden** [comment]
Create car.kv file and paste this:

```
#:kivy 1.0.9
# ref: https://kivy.org/docs/tutorials/pong.html

<Car>:
    size: 20, 10
    canvas:
        PushMatrix
        Rotate:
            angle: self.angle
            origin: self.center
        Rectangle:
            pos: self.pos
            size: self.size
        PopMatrix

<Ball1>:
    size: 10,10
    canvas:
        Color:
            rgba: 1,0,0,1
        Ellipse:
            pos: self.pos
            size: self.size
<Ball2>:
    size: 10,10
    canvas:
        Color:
            rgba: 0,1,1,1
        Ellipse:
            pos: self.pos
            size: self.size

<Ball3>:
    size: 10,10
    canvas:
        Color:
            rgba: 1,1,0,1
        Ellipse:
            pos: self.pos
            size: self.size

<Game>:
    car: game_car
    ball1: game_ball1
    ball2: game_ball2
    ball3: game_ball3

    Car:
        id: game_car
        center: self.parent.center
    Ball1:
        id: game_ball1
        center: self.parent.center
    Ball2:
        id: game_ball2
        center: self.parent.center
    Ball3:
        id: game_ball3
        center: self.parent.center
```
